export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
export const REMOVE_PRODUCT_FROM_CART = 'REMOVE_PRODUCT_FROM_CART';
export const INCREMENT_CART_ITEM_QUANTITY = 'INCREMENT_CART_ITEM_QUANTITY';
export const DECREMENT_CART_ITEM_QUANTITY = 'DECREMENT_CART_ITEM_QUANTITY';
export const ADD_FAVOURITES = 'ADD_FAVOURITES';
export const GET_PRODUCTS_FROM_API = 'GET_PRODUCTS_FROM_API';
export const REMOVE_PRODUCT_FROM_FAV = 'REMOVE_PRODUCT_FROM_FAV';
